# 目的
sampleモデルファイルの内容を確認するためのノート。


In [1]:
from keras.models import Sequential, load_model
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Activation, Flatten, Embedding, Reshape,Convolution1D
from keras.utils import np_utils
from keras import backend as K
import numpy as np

Using TensorFlow backend.


サンプルとして、隠れ層一つの３層NNをMnistで作成する。

In [33]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [34]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

In [35]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [36]:
Y_train = np_utils.to_categorical(y_train, 10)

In [37]:
Y_test = np_utils.to_categorical(y_test, 10)

In [38]:
model = Sequential()
model.add(Flatten(input_shape=input_shape))
model.add(Dense(128,input_dim=28*28))
model.add(Activation('relu'))
model.add(Dense(10,input_dim=100))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [39]:
model.fit(X_train,Y_train,batch_size=100,nb_epoch=10,verbose=1,validation_data=(X_test,Y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s - loss: 0.4733 - acc: 0.8756 - val_loss: 0.2689 - val_acc: 0.9264
Epoch 2/10
60000/60000 [==============================] - 2s - loss: 0.2462 - acc: 0.9321 - val_loss: 0.2133 - val_acc: 0.9407
Epoch 3/10
60000/60000 [==============================] - 2s - loss: 0.1993 - acc: 0.9438 - val_loss: 0.1810 - val_acc: 0.9492
Epoch 4/10
60000/60000 [==============================] - 2s - loss: 0.1689 - acc: 0.9530 - val_loss: 0.1567 - val_acc: 0.9552
Epoch 5/10
60000/60000 [==============================] - 2s - loss: 0.1469 - acc: 0.9583 - val_loss: 0.1414 - val_acc: 0.9600
Epoch 6/10
60000/60000 [==============================] - 2s - loss: 0.1300 - acc: 0.9636 - val_loss: 0.1322 - val_acc: 0.9633
Epoch 7/10
60000/60000 [==============================] - 2s - loss: 0.1169 - acc: 0.9670 - val_loss: 0.1202 - val_acc: 0.9653
Epoch 8/10
60000/60000 [==============================] - 2s 

# 単体テスト用データ作成
Convolution1D, Dense, Embedding, Flatten, Relu, Sigmoid, Softmax, Tanhの単位テストのために、入力データ、モデルデータ、正解データをそれぞれ作成し、出力する。

## Convolution1D

In [26]:
# Model 作成
modelConv = Sequential()
modelConv.add(Convolution1D(2, 3, border_mode='same', input_shape=(10, 12)))
modelConv.compile(loss='categorical_crossentropy', optimizer='adadelta', metrics=['accuracy'])

In [27]:
# 入力データ
X_train = np.random.rand(1, 10, 12)

In [28]:
y_train = np.random.randint(2, size=(10))

In [29]:
Y_train = np_utils.to_categorical(y_train, 2)

In [30]:
Y_train = Y_train.reshape(1, 10, 2)

In [33]:
modelConv.fit(X_train, Y_train, nb_epoch=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s - loss: 4.8849 - acc: 0.5000
Epoch 2/10
1/1 [==============================] - 0s - loss: 4.8838 - acc: 0.5000
Epoch 3/10
1/1 [==============================] - 0s - loss: 4.8838 - acc: 0.5000
Epoch 4/10
1/1 [==============================] - 0s - loss: 4.8828 - acc: 0.5000
Epoch 5/10
1/1 [==============================] - 0s - loss: 4.8821 - acc: 0.5000
Epoch 6/10
1/1 [==============================] - 0s - loss: 4.8818 - acc: 0.5000
Epoch 7/10
1/1 [==============================] - 0s - loss: 4.8806 - acc: 0.5000
Epoch 8/10
1/1 [==============================] - 0s - loss: 4.8809 - acc: 0.5000
Epoch 9/10
1/1 [==============================] - 0s - loss: 4.8801 - acc: 0.5000
Epoch 10/10
1/1 [==============================] - 0s - loss: 4.8795 - acc: 0.5000


In [34]:
# 正解データ
Y_gold = modelConv.predict(X_train)

In [35]:
Y_gold

array([[[ -2.88217455e-01,   6.81861579e-01],
        [ -5.38490713e-01,   6.20526560e-02],
        [ -3.18091482e-01,  -7.48135746e-02],
        [ -2.35468820e-02,   4.07085158e-02],
        [ -4.85583872e-01,   2.24703625e-01],
        [ -4.50441420e-01,   2.71697552e-03],
        [ -1.76823571e-01,   4.89799917e-01],
        [ -1.23186730e-01,   5.74909784e-02],
        [ -3.36253673e-01,  -8.40994492e-02],
        [  5.95557541e-02,   3.20440391e-04]]], dtype=float32)

In [39]:
# 保存
Y_gold = Y_gold.reshape(10,2)

In [48]:
goldF = open('./data/unitTest/convolutino1d_gold.csv', 'w')
for data in Y_gold:
    goldF.write('%1.15f' % data[0] + ',' '%1.15f' % data[1] + '\n')
goldF.close()

In [51]:
X_train.shape

(1, 10, 12)

In [52]:
X_train = X_train.reshape(10, 12)

In [66]:
inputF = open('./data/unitTest/convolutino1d_input.csv','w')
for i in range(0,10):
    inputF.write(','.join(['%1.15f' % d for d in X_train[i]]) + '\n')
inputF.close()

In [67]:
modelConv.save('./data/unitTest/convolutino1d_model.h5')

## Dense


In [101]:
modelDense = Sequential()
modelDense.add(Dense(2,input_dim=10))
modelDense.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [102]:
X_input_dense = np.random.rand(10)

In [103]:
X_input_dense = X_input_dense.reshape(1, 10)

In [104]:
y_input_dense = [1]

In [105]:
Y_input_dense = np_utils.to_categorical(y_input_dense, 2)

In [106]:
Y_input_dense.shape

(1, 2)

In [107]:
modelDense.fit(X_input_dense, Y_input_dense)

Epoch 1/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 2/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 3/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 4/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 5/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 6/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 7/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 8/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 9/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000
Epoch 10/10
1/1 [==============================] - 0s - loss: 1.1921e-07 - acc: 1.0000


In [108]:
Y_gold_dense = modelDense.predict(X_input_dense)

In [109]:
Y_gold_dense = Y_gold_dense.reshape(2)

In [110]:
X_input_dense = X_input_dense.reshape(10)

In [111]:
# 保存
inputF = open('./data/unitTest/dense/dense_input.csv','w')
inputF.write(','.join(['%1.15f' % d for d in X_input_dense]) + '\n')
inputF.close()

In [112]:
goldF = open('./data/unitTest/dense/dense_gold.csv','w')
goldF.write(','.join(['%1.15f' % d for d in Y_gold_dense]) + '\n')
goldF.close()

In [113]:
Y_input_dense[0]

array([ 0.,  1.])

In [114]:
Y_gold_dense

array([-0.26505464,  0.81915766], dtype=float32)

In [115]:
modelDense.save('./data/unitTest/dense/dense_model.h5')