# 目的
sampleモデルファイルの内容を確認するためのノート。


In [1]:
from keras.models import Sequential, load_model
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Activation, Flatten, Embedding, Reshape,Convolution1D
from keras.utils import np_utils
from keras import backend as K
import numpy as np

Using TensorFlow backend.


サンプルとして、隠れ層一つの３層NNをMnistで作成する。

In [9]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [14]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

In [16]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [17]:
Y_train = np_utils.to_categorical(y_train, 10)

In [18]:
Y_test = np_utils.to_categorical(y_test, 10)

In [51]:
model = Sequential()
model.add(Flatten(input_shape=input_shape))
model.add(Dense(128,input_dim=28*28))
model.add(Activation('relu'))
model.add(Dense(10,input_dim=100))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [52]:
model.fit(X_train,Y_train,batch_size=100,nb_epoch=10,verbose=1,validation_data=(X_test,Y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s - loss: 0.4751 - acc: 0.8749 - val_loss: 0.2727 - val_acc: 0.9242
Epoch 2/10
60000/60000 [==============================] - 2s - loss: 0.2455 - acc: 0.9318 - val_loss: 0.2138 - val_acc: 0.9402
Epoch 3/10
60000/60000 [==============================] - 2s - loss: 0.1982 - acc: 0.9449 - val_loss: 0.1795 - val_acc: 0.9490
Epoch 4/10
60000/60000 [==============================] - 2s - loss: 0.1676 - acc: 0.9536 - val_loss: 0.1578 - val_acc: 0.9530
Epoch 5/10
60000/60000 [==============================] - 3s - loss: 0.1460 - acc: 0.9592 - val_loss: 0.1417 - val_acc: 0.9584
Epoch 6/10
60000/60000 [==============================] - 3s - loss: 0.1295 - acc: 0.9636 - val_loss: 0.1266 - val_acc: 0.9639
Epoch 7/10
60000/60000 [==============================] - 4s - loss: 0.1163 - acc: 0.9675 - val_loss: 0.1196 - val_acc: 0.9638
Epoch 8/10
60000/60000 [==============================] - 4s 

In [40]:
X_pred = model.predict_classes(X_test)

 9952/10000 [============================>.] - ETA: 0s

In [44]:
X_pred[1]

2

In [45]:
Y_test[1]

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [46]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
flatten_8 (Flatten)              (None, 784)           0           flatten_input_7[0][0]            
____________________________________________________________________________________________________
dense_6 (Dense)                  (None, 100)           78500       flatten_8[0][0]                  
____________________________________________________________________________________________________
activation_4 (Activation)        (None, 100)           0           dense_6[0][0]                    
____________________________________________________________________________________________________
dense_7 (Dense)                  (None, 10)            1010        activation_4[0][0]               
___________________________________________________________________________________________

In [53]:
model.save('./data/keras_sample.h5')

In [54]:
X_pred = model.predict_classes(X_test,verbose=1)

 9888/10000 [============================>.] - ETA: 0s

In [2]:
model2 = Sequential()
model2.add(Flatten(input_shape=(5,2,)))
#model2.add(Activation('softmax',input_shape=(2,5,)))
model2.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [96]:
test = np.array((1,2,3,4,5,6,7,8,9,10))
gold = np.array((0,0,0,0,1,0,0,0,0,1))

In [97]:
test = test.reshape(1,5,2)
gold = gold.reshape(1,5,2)

In [98]:
model2.predict(test)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]], dtype=float32)

In [99]:
test

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [3]:
from keras.utils.visualize_util import plot

AttributeError: module 'pydot' has no attribute 'find_graphviz'