# 目的
sampleモデルファイルの内容を確認するためのノート。


In [1]:
from keras.models import Sequential, load_model
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Activation, Flatten, Embedding, Reshape,Convolution1D
from keras.utils import np_utils
from keras import backend as K
import numpy as np

Using TensorFlow backend.


サンプルとして、隠れ層一つの３層NNをMnistで作成する。

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [5]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

In [6]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

In [7]:
Y_train = np_utils.to_categorical(y_train, 10)

In [8]:
Y_test = np_utils.to_categorical(y_test, 10)

In [9]:
model = Sequential()
model.add(Flatten(input_shape=input_shape))
model.add(Dense(128,input_dim=28*28))
model.add(Activation('relu'))
model.add(Dense(10,input_dim=100))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [10]:
model.fit(X_train,Y_train,batch_size=100,nb_epoch=10,verbose=1,validation_data=(X_test,Y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 3s - loss: 0.4771 - acc: 0.8746 - val_loss: 0.2623 - val_acc: 0.9271
Epoch 2/10
60000/60000 [==============================] - 2s - loss: 0.2397 - acc: 0.9332 - val_loss: 0.2054 - val_acc: 0.9425
Epoch 3/10
60000/60000 [==============================] - 3s - loss: 0.1933 - acc: 0.9461 - val_loss: 0.1758 - val_acc: 0.9493
Epoch 4/10
60000/60000 [==============================] - 3s - loss: 0.1639 - acc: 0.9542 - val_loss: 0.1537 - val_acc: 0.9542
Epoch 5/10
60000/60000 [==============================] - 4s - loss: 0.1428 - acc: 0.9598 - val_loss: 0.1360 - val_acc: 0.9602
Epoch 6/10
60000/60000 [==============================] - 3s - loss: 0.1269 - acc: 0.9643 - val_loss: 0.1290 - val_acc: 0.9624
Epoch 7/10
60000/60000 [==============================] - 3s - loss: 0.1140 - acc: 0.9682 - val_loss: 0.1178 - val_acc: 0.9658
Epoch 8/10
60000/60000 [==============================] - 3s 

In [11]:
X_pred = model.predict_classes(X_test)

 9856/10000 [============================>.] - ETA: 0s

In [12]:
X_pred[1]

2

In [13]:
Y_test[1]

array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
flatten_1 (Flatten)              (None, 784)           0           flatten_input_1[0][0]            
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 128)           100480      flatten_1[0][0]                  
____________________________________________________________________________________________________
activation_1 (Activation)        (None, 128)           0           dense_1[0][0]                    
____________________________________________________________________________________________________
dense_2 (Dense)                  (None, 10)            1290        activation_1[0][0]               
___________________________________________________________________________________________

In [15]:
#model.save('./data/keras_sample.h5')

In [16]:
X_pred = model.predict_classes(X_test,verbose=1)

 9984/10000 [============================>.] - ETA: 0s

In [24]:
model2 = Sequential()
model2.add(Flatten(input_shape=(2,5,)))
#model2.add(Activation('softmax',input_shape=(2,5,)))
model2.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [25]:
test = np.array((1,2,3,4,5,6,7,8,9,10))
gold = np.array((0,0,0,0,1,0,0,0,0,1))

In [26]:
test = test.reshape(1,5,2)
gold = gold.reshape(1,5,2)

In [29]:
test = test.transpose().reshape(1,2,5)
gold = gold.transpose().reshape(1,2,5)

In [30]:
model2.predict(test)

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]], dtype=float32)

In [31]:
test

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])